repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-json
        exclude: tsconfig.json
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
