name: code-checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  code-cheks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn run prettier
      - run: yarn run lint
